### PR TITLE
Add subscribe_to_webhooks, search_company and request_company.

### PR DESCRIPTION
**Pull request by crova**
# Comment
This implements `subscribe_to_webhooks`, `search_company` and `request_company`.

Let me know if you see any issues.

Cheers.

### CODE REVIEW

**Review by imricardoramos — CHANGES_REQUESTED** [review]
Looks good! Although could we make `app_secret` and `app_id` configurable through `config.exs`/`runtime.exs`?

**Comment by neilberkman** [comment]
> Looks good! Although could we make `app_secret` and `app_id` configurable through `config.exs`/`runtime.exs`?

@crova I know I specified that we should pass in the key / ID each time but I've changed my mind 🙂 Let's use `runtime.exs`.

**Comment by crova** [comment]
Hopefully I got this request right.
 
 Let me know if you see any issues.
 
 Cheers.

**Review by imricardoramos — APPROVED** [review]
LGTM!

**Pull request merged**
